FROM python:3.7.9-buster

ARG ADMWEB_APP_DIR
ARG MIGRATIONS_DIR
WORKDIR /app
COPY ${ADMWEB_APP_DIR}/requirements.txt requirements.txt
RUN pip install -r requirements.txt

ENV TZ JST-9
COPY ${ADMWEB_APP_DIR}/run.py ./
COPY ${ADMWEB_APP_DIR}/application ./application
COPY ${MIGRATIONS_DIR} ./migrations
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV APP_PORT 5000
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "flask run --host 0.0.0.0 --port ${APP_PORT}"]
