"""empty message

Revision ID: 42c39727923a
Revises: 
Create Date: 2021-03-03 01:00:25.858077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c39727923a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('display_name', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=256, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('password', sa.String(length=1024, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('start_hour', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('start_minites', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('end_hour', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('end_minites', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('master', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ownersData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('start_spot', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('goal_spot', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('car_class', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('car_num', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('child', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('car_status', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('display_status', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('display_date', sa.DateTime(), nullable=True),
    sa.Column('owner_delete_status', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('nosmoke', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('wd4', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('studless', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('remarks', sa.String(length=250, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_status', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_name', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_number', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_mail', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_check', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_take_date', sa.DateTime(), nullable=True),
    sa.Column('user_return_date', sa.DateTime(), nullable=True),
    sa.Column('user_price', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('user_remarks', sa.String(length=250, collation='utf8mb4_general_ci'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('display_name', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('email', sa.String(length=256, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('password', sa.String(length=1024, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ownersData')
    op.drop_table('owners')
    # ### end Alembic commands ###
