"""empty message

Revision ID: 8ec00e1121ac
Revises: 5c3661192af0
Create Date: 2021-03-02 01:54:10.138026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec00e1121ac'
down_revision = '5c3661192af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piyo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50, collation='utf8mb4_general_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('piyo')
    # ### end Alembic commands ###
